services:
    # app:
    # build: .                
    # container_name: aita_app
    # ports:
    #   - "8080:8080"
    # environment:
    #   - REDIS_HOST=aita_redis 
    #   - DB_HOST=aita_postgres_v2
    #   - APP_ENV=production 
    # networks:
    #   - aita_network
    # depends_on:
    #   - redis
    #   - postgres
      
  postgres:
    image: postgres:15-alpine
    container_name: aita_postgres_v2  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" 
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    networks:
      - aita_network

  redis:
    image: redis:7-alpine
    container_name: aita_redis
    ports:
      - "${REDIS_PORT}:6379"  
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"] 
    networks:
      - aita_network

networks:
  aita_network:
    driver: bridge

volumes:
  postgres_data_v2:
  redis_data:


