version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aita_postgres_v2  
    environment:
      POSTGRES_USER: 'aita_admin'
      POSTGRES_PASSWORD: 'password' 
      POSTGRES_DB: 'aita_db'
    ports:
      - "5439:5432" 
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:


